### PR TITLE
Speed Up Build Process

### PR DESCRIPTION
**Pull request by gabrielsomoza**
Using dist files (the composer default) should speed up the build process considerably.

### CODE REVIEW

**Comment by gabrielsomoza** [comment]
Wow, its taking upwards from 30 min to build branches like `develop` and `master`.. not sure this alone would help but its a start.

**Comment by ezimuel** [comment]
@gabrielsomoza we used --prefer-source for the Travis-CI + Github API limitation, see details [here](https://github.com/composer/composer/issues/1314). We should investigate in other solutions, like [this one](https://blog.wyrihaximus.net/2015/09/github-auth-token-on-travis/) but for now we cannot remove the --prefer-source flag.

**Comment by jguittard** [comment]
@ezimuel I already talked with @weierophinney about https://continuousphp.com
All the builds are parallelized, it's damn fast and have no API limitation.
Feel free to ping me if you want to know more.

**Comment by ezimuel** [comment]
@jguittard that's another interesting possibility! We should have a meeting on that, thanks!

**Comment by jguittard** [comment]
@ezimuel anytime. Let's schedule a call with @weierophinney and discuss about that.

**Comment by fdewinne** [comment]
@ezimuel let's talk about that at PHPBenelux! ;)

**Comment by jguittard** [comment]
@ezimuel @fdewinne Wish I could be there :(

**Comment by ezimuel** [comment]
@fdewinne awesome, thanks! I cannot wait to be there :)

**Comment by gabrielsomoza** [comment]
@ezimuel oh, I didn't know about this problem. But using `--no-interaction` doesn't fall back to clone if the rate limit is reached? Jordi seemed quite sure that's what would happen.

**Comment by ezimuel** [comment]
@gabrielsomoza I'll check, thanks!

**Pull request closed without merging**
