### PR TITLE
resolve \ZF\Hal\Entity::$entity deprecation warnings

### PR DESCRIPTION
**Pull request by abacaphiliac**
resolves \ZF\Hal\Entity::$entity deprecation warnings that come along with upgrading zfcampus/zf-hal from ^1.3 to ^1.4.

i also took care of some alerts that came up due to recent code sniffer changes, and a fatal error on a non-existent \ZFTest\Configuration\TestAsset\ConfigWriter class. i looked at some neighboring classes and found that they used an aliased \Zend\Config\Writer\PhpArray, so i thought that would be acceptable. i'd be happy to split this merge request if necessary.

i noticed that this package is being prepped for ZF3. i understand that my merge request supports a soon-to-be old version of this package. if you choose to accept my merge request, i'd be happy to resolve conflicts in #348, or any other merge request that moves us forward.

### CODE REVIEW

**Comment by weierophinney** [comment]
The problem here is that `getEntity()` was only added starting in 1.4.0. As such, updating the code to use that method *without also updating the zf-hal dependency to `^1.4`* will cause errors for folks who update, but stay on a pre-1.4 version of zf-hal.

As such, these are the approaches we can take to resolve the issues:

- Users encountering the problem can update their project skeleton's `composer.json` to specify `"zf-hal": "~1.3.0"`; this will get them the latest in the 1.3 series, and eliminate the deprecation notices. When they are ready to update, they can remove that entry from `composer.json`.
- Users may also setup PHP's error reporting to remove `E_USER_DEPRECATED` notices, which will allow the code to continue working. (Note: they will likely want to re-enable this eventually!).
- Finally, the proper solution, as already noted, is to update the zf-hal dependency when making the code changes suggested in this pull request. *We typically only bump dependency minor requirements when doing a minor release, however,* which means that #348 supercedes this pull request, as it already accomplishes those changes.

**Comment by abacaphiliac** [comment]
ah of course! sorry that i missed that. and thank you for the very thorough reply.

**Comment by weierophinney** [comment]
That said... I was just testing some stuff with zf-apigility-admin-ui against the current releases of zf-apigility-admin, and this is definitely a mess.

I'm going to create a pull request that does the following:

```php
$entity = method_exists($halEntity, 'getEntity') ? $halEntity->getEntity() : $halEntity->entity;
```

That will cover the BC concerns, while ensuring the admin UI doesn't fail due to the admin API raising deprecation notices.

> ### how to workaround the problem
> 
> I worked around the problem by adding this at the top of `public/index.php`:
> 
> ```php
> error_reporting(E_ALL & ~E_USER_DEPRECATED);
> ```
>
> However, we cannot expect users to know that they need to do that on upgrade!

**Comment by abacaphiliac** [comment]
i've applied your workaround in my app and will happily remove it when your BC change is in place. thanks!

**Comment by weierophinney** [comment]
#350 is my proposed solution, and assuming tests pass, I'll do a 1.4.3 release immediately.

**Pull request closed without merging**
