### PR TITLE
Add doctrine to UI

### PR DESCRIPTION
**Pull request by Hounddog**
this is no where ready yet.

Just want to provide a pr so people can view it.

Currently possible:
Configure Doctrine adapter.

To-do:
Create Rest with doctrine-connected.

### CODE REVIEW

**Comment by kusmierz** [comment]
@Hounddog @weierophinney @jguittard any news here?

**Comment by jguittard** [comment]
Available in develop branch and eventually in 1.1 RC

**Comment by jguittard** [comment]
@AlexeyKosov @netiul @kusmierz Available in develop branch and eventually in 1.1 RC

**Comment by netiul** [comment]
:+1:

**Comment by jguittard** [comment]
Should be closed in favor of #258

**Pull request closed without merging**
