### PR TITLE
DB Autodiscovery + Doctrine adapters support

### PR DESCRIPTION
**Pull request by jguittard**

### CODE REVIEW

**Comment by TomHAnderson** [comment]
Yes, I can help.  I just setup an install with both your PRs.  How do I use it?  Please provide a few directions so I know where to start visually in the admin.

**Comment by ezimuel** [comment]
@TomHAnderson and @jguittard I just pushed the new Admin UI in the develop branch of [zf-apigility-admin-ui](https://github.com/zfcampus/zf-apigility-admin-ui/tree/develop). Any news on this PR?

**Comment by TomHAnderson** [comment]
@jguittard Please provide a list of steps to test this.

**Comment by jguittard** [comment]
As discussed with @ezimuel, upon REST model service request, a listener for Doctrine REST service is attached only if Doctrine Admin module is enabled.

**Pull request merged**
