### PR TITLE
Minor Typo Fix

### PR DESCRIPTION
**Pull request by takethefake**
Notices a minor typo in RpcServiceModel

### CODE REVIEW

**Comment by gabrielsomoza** [comment]
:+1:

**Comment by alex-patterson-webdev** [comment]
I see this is in 1.4, I am using 1.2.* for PHP 5.4 support and the error is still present.

**Comment by alex-patterson-webdev** [comment]
It seems to have been introduced in v1.0.5.

**Comment by ezimuel** [comment]
@alex-patterson-webdev I just tagged also [1.2.2](https://github.com/zfcampus/zf-apigility-admin/tree/1.2.2)

**Comment by alex-patterson-webdev** [comment]
@ezimuel Thanks!

**Pull request merged**
