### PR TITLE
Fixes #264 : Adds verifications for Apigility Doctrine modules

### LINKED ISSUE #264: Doctrine Autodiscovery is missing
In the current develop branch at the new UI creating Doctrine-Connected service is not working. After selecting Entity Manager apigility is trying to point non-existing API end-point which is `/apigility/api/module/DemoAPI/1/autodiscovery/doctrine/doctrine.entitymanager.orm_default`.

This route doesn't exists. I didn't found any code implementing this feature. Bug? Or am I missing something?

apigility_doctrine_connected_error

### PR DESCRIPTION
**Pull request by jguittard**
Also removed Doctrine Adapters payload for Dashboard service

### CODE REVIEW

**Comment by ezimuel** [comment]
@jguittard I like the idea of checking for Doctrine module but in this way we'll have a **500 Error** in the UI, as result for the HTTP call `/api/doctrine-adapter`. Instead of throwing an Exception we can give a **204** HTTP result (*Ok with no content*). In this way we don't have a 500 Error and we can manage the result in a different way in the UI. We can enable the Doctrine tab only if the HTTP status is 200.

**Comment by ezimuel** [comment]
@jguittard any news on this? Thanks.

**Comment by ezimuel** [comment]
@jguittard the PR https://github.com/zfcampus/zf-rest/issues/68 has been fixed. Now it's possible to return a Zend\Http\Response directly in a REST Resource.

**Comment by jguittard** [comment]
@ezimuel Implemented Zend\Http\Response return in DoctrineAdapterResource

**Pull request merged**
